name: Infra ci
on:
  pull_request:
    branches: [main]
    paths:
      - "infra/**"

permissions:
  id-token: write
  pull-requests: write
  contents: read
  packages: write

jobs:
  fmt:
    name: "Terraform fmt check"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Terraform fmt check
        run: echo "fake terraform fmt check"

  validate:
    name: "Terraform validate check"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Terraform validate check
        run: echo "fake terraform validate"
        env:
          TF_VAR_image_tag: "latest"
  plan:
    name: "Terraform plan"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Plan LLM Slackbot staging deployment
        id: plan_llmslackbot_staging_deployment
        working-directory: infra/tg
        run: echo "fake terraform plan"
        continue-on-error: true
