name: Build
on:
  push:
    branches:
      - "**"

jobs:
  oras:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: octo-sts/action@6177b4481c00308b3839969c3eca88c96a91775f # v1.0.0
        id: octo-sts
        with:
          # can only run on main branch
          scope: amber-beasley-liatrio/learning-actions
          identity: semantic-release
      - name: Setup oras
        uses: oras-project/setup-oras@v1
      - name: Oras version
        run: oras version
      - name: Oras login
        run: echo "${{ steps.octo-sts.outputs.token }}" | oras login ghcr.io --username ${{ github.actor }} --password-stdin
      - name: Oras push
        run: oras push ghcr.io/someorg/policy-hello:1.0.0
