name: Build
on:
  push:
    branches:
      - "**"

jobs:
  oras:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Setup oras
        uses: oras-project/setup-oras@v1
      - name: Oras version
        run: oras version
      - name: Oras login
        run: oras login ghcr.io --username ${{ github.actor }} --password ${{ github.token }}
      - name: Oras push
        run: oras push ghcr.io/someorg/policy-hello:1.0.0
