name: Build
on:
  push:
    branches:
      - "*"

permissions:
  id-token: write
  contents: read
  attestations: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create evaluation-results.json
        run: echo "{}" > evaluation-results.json

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: evaluation-results
          path: evaluation-results.json
  go-semantic-release:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: octo-sts/action@6177b4481c00308b3839969c3eca88c96a91775f # v1.0.0
        id: octo-sts
        with:
          scope: amber-beasley-liatrio/learning-actions
          identity: main-semantic-release

      - name: Run go-semantic-release
        uses: go-semantic-release/action@v1
        with:
          github-token: amber-beasley-liatrio/learning-actions
          changelog-generator-opt: emojis=true
          allow-initial-development-versions: true
