name: Build
on:
  push:
    branches:
      - "**"

jobs:

  anchore-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Scan current project
        uses: anchore/scan-action@v3
        id: anchore-scan
        with:
          path: "."
          output-format: "json"
          fail-build: "false"
    
      - name: Upload CodeQL results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.anchore-scan.outputs.json }}
          path: ${{ steps.anchore-scan.outputs.json }}

  codeql:
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: ./.github/workflows/codeql.yaml

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create evaluation-results.json
        run: echo "{}" > evaluation-results.json

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: evaluation-results
          path: evaluation-results.json

  go-semantic-release:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: evaluation-results

      - uses: octo-sts/action@6177b4481c00308b3839969c3eca88c96a91775f # v1.0.0
        id: octo-sts
        with:
          # can only run on main branch
          scope: amber-beasley-liatrio/learning-actions
          identity: semantic-release

      - name: Run go-semantic-release
        id: go-semantic-release
        uses: go-semantic-release/action@v1
        with:
          github-token: ${{ steps.octo-sts.outputs.token }}
          changelog-generator-opt: emojis=true
          allow-initial-development-versions: true

      - name: Upload Results/Sigstore Bundle as Release Asset
        if: steps.go-semantic-release.outputs.version != ''
        uses: softprops/action-gh-release@01570a1f39cb168c169c802c3bceb9e93fb10974 # v2.1.0
        with:
          files: evaluation-results.json
          tag_name: v${{ steps.go-semantic-release.outputs.version }}
          token: ${{ steps.octo-sts.outputs.token }}
