name: Build
on:
  push:
    branches:
      - "**"

jobs:
  oras:
    runs-on: ubuntu-latest
    steps:
      - uses: oras-project/setup-oras@v1
      - run: |
          oras version
          oras login ghcr.io --username ${{ github.actor }} --password ${{ github.token }}
  
