name: Build
on:
  push:
    branches:
      - "**"

env:
  OPA_VERSION: 0.67.1
  REGAL_VERSION: 0.28.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup OPA
        uses: open-policy-agent/setup-opa@34a30e8a924d1b03ce2cf7abe97250bbb1f332b5 #v2.2.0
        with:
          version: ${{ env.OPA_VERSION }}
      - name: Build OPA Bundle
        run: |
          opa \
            build \
            --bundle ./policies \
            --ignore "*_test.rego" \
            --output bundle.tar.gz

  oras:
    needs: build
    permissions:
      contents: write
      packages: write
      #id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      # - uses: octo-sts/action@6177b4481c00308b3839969c3eca88c96a91775f # v1.0.0
      #   id: octo-sts
      #   with:
      #     # can only run on main branch
      #     scope: amber-beasley-liatrio/learning-actions
      #     identity: semantic-release
      ### ${{ steps.octo-sts.outputs.token }}
      - name: Setup oras
        uses: oras-project/setup-oras@v1
      - name: Oras version
        run: oras version
      - name: Oras login
        run: echo "${{ github.token }}" | oras login ghcr.io --username ${{ github.actor }} --password-stdin
      - name: Oras push
        run: oras push ghcr.io/amber-beasley-liatrio/policy-hello:1.0.0 --config config.json:application/vnd.oci.image.config.v1+json bundle.tar.gz:application/vnd.oci.image.layer.v1.tar+gzip
