name: Build

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create evaluation-results.json
        run: echo '{}' > evaluation-results.json

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: evaluation-results
          path: evaluation-results.json